version: "3.8"
services:
  {{ cookiecutter.postgres_host }}:
    container_name: 'postgres_{{ cookiecutter.project_slug }}'
    image: postgres:15
    command: postgres -c "max_connections=10000"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - {{ cookiecutter.project_slug }}
    ports:
      - ${POSTGRES_PORT}:5432
  pg_web:
    container_name: 'postgres_{{ cookiecutter.project_slug }}_web'
    image: sosedoff/pgweb
    restart: unless-stopped
    ports:
      - "8081:8081"
    links:
      - {{ cookiecutter.postgres_host }}:postgres  # my database container is called postgres, not db
    env_file:
      - .env
    environment:
      - PGWEB_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - {{ cookiecutter.postgres_host }} # my database container is called postgres, not db
    networks:
      - {{ cookiecutter.project_slug }}_network
  {{ cookiecutter.project_slug }}_app:
    build: .
    restart: unless-stopped
    container_name: "{{ cookiecutter.project_slug }}"
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8787"
    networks:
      - {{ cookiecutter.project_slug }}
    depends_on:
      - {{ cookiecutter.postgres_host }}
      - pg_web
networks:
  {{ cookiecutter.project_slug }}_network:
    external: false
