version: "3.8"
services:
  {{ cookiecutter.postgres_host }}:
    container_name: 'postgres_{{ cookiecutter.project_slug }}'
    image: postgres:15
    command: postgres -c "max_connections=10000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - {{ cookiecutter.path_to_project_production }}:/var/lib/postgresql/data
    networks:
      - {{ cookiecutter.project_slug }}_network
    ports:
      - ${POSTGRES_PORT_TO_LOCAL_HOST}:5432
  {{ cookiecutter.project_slug }}_app:
    build: .
    restart: unless-stopped
    container_name: "{{ cookiecutter.project_slug }}"
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8787"
    volumes:
      - {{ cookiecutter.path_to_project }}/{{ cookiecutter.project_slug }}/logs:/app/logs
    networks:
      - {{ cookiecutter.project_slug }}_network
    depends_on:
      - {{ cookiecutter.postgres_host }}
      - pg_web
networks:
  {{ cookiecutter.project_slug }}_network:
    external: false
